export const BASE_URL = "http://localhost:3005"

export const GET_POST_DATA = "GET_POST_DATA"
export const GET_USER_LOGIN_DATA = "GET_USER_LOGIN_DATA"
export const LOGOUT_USER = "LOGOUT_USER"
export const GET_POST_BY_ID_DATA = "GET_POST_BY_ID_DATA"

export const GET_POST_SUCCESS = "GET_ALL_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_ALL_POST_FAILURE"

export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS"
export const GET_POST_BY_ID_FAILURE = "GET_POST_BY_ID_FAILURE"

export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

// export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS"
// export const GET_SINGLE_POST_FAILURE = "GET_SINGLE_POST_FAILURE"

// export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS"
// export const GET_ALL_POST_FAILURE = "GET_ALL_POST_FAILURE"
